-- AlterTable
ALTER TABLE `action_history` MODIFY `device` ENUM('LED', 'FAN', 'AIR_CONDITIONER', 'GAS_WARNING') NOT NULL;

-- AlterTable
ALTER TABLE `sensor_data` ADD COLUMN `gas` INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE `GasWarning` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `gasValue` DOUBLE NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
